#!/bin/bash

ip link add d0 type dummy || {
        echo "Skipping, no dummy interface available"
        exit 0
}
trap "ip link del d0" EXIT

ip link add d1 type dummy || {
        echo "Skipping, no dummy interface available"
        exit 0
}
trap "ip link del d1" EXIT

ip link add d2 type dummy || {
        echo "Skipping, no dummy interface available"
        exit 0
}
trap "ip link del d2" EXIT

set -e

RULESET="table netdev x {
	chain y {
		type filter hook ingress priority 0; policy accept;
	}
}"

$NFT -f - <<< "$RULESET"

$NFT add chain netdev x y '{ devices = { d0 }; }'
$NFT add chain netdev x y '{ devices = { d1, d2, lo }; }'
$NFT delete chain netdev x y '{ devices = { lo }; }'
