#!/bin/bash

# Tests use of variable before definition.

set -e

tmpfile=$(mktemp)
if [ ! -w $tmpfile ] ; then
	echo "Failed to create tmp file" >&2
	exit 0
fi

trap "rm -rf $tmpfile" EXIT # cleanup if aborted

echo "
define var2 = \$var1
define var1 = lo

table ip t {
	chain c {
		iif \$var2
	}
}" >> $tmpfile

$NFT -f $tmpfile
