#!/bin/bash

# Tests recursive definition of a variable.

set -e

tmpfile=$(mktemp)
if [ ! -w $tmpfile ] ; then
	echo "Failed to create tmp file" >&2
	exit 0
fi

trap "rm -rf $tmpfile" EXIT # cleanup if aborted

echo "
define var1 = \$var1

table ip t {
	chain c {
		iif \$var1
	}
}" >> $tmpfile

$NFT -f $tmpfile
