#!/bin/bash

set -e

RULESET="define x = {
        1.1.1.1 : 2,
        * : 3,
}

table ip x {
        map y {
                typeof ip saddr : mark
                elements = \$x
        }
        map z {
                typeof ip saddr : mark
                elements = \$x
        }
}"

$NFT -f - <<< "$RULESET"
