#!/bin/bash

RULESET="table ip mangle {
	set blackhole {
		type ipv4_addr
		elements = { 192.168.1.4, 192.168.1.5 }
	}

	chain prerouting {
		type filter hook prerouting priority 0; policy accept;
		tcp dport { ssh, http } accept
		ip saddr @blackhole drop
		icmp type echo-request accept
		iifname \"lo\" accept
		icmp type echo-request counter packets 0 bytes 0
		ct state established,related accept
		tcp flags != syn counter packets 7 bytes 841
		ip saddr 192.168.1.100 ip daddr 192.168.1.1 counter packets 0 bytes 0
	}
}
table arp x {
	chain y {
		arp htype 22
		arp ptype ip
		arp operation != rrequest
		arp operation { request, reply, rrequest, rreply, inrequest, inreply, nak }
		arp hlen 33-45
	}
}
table bridge x {
	chain y {
		type filter hook input priority 0; policy accept;
		vlan id 4094
		vlan id 4094 vlan cfi 0
		vlan id 1 ip saddr 10.0.0.0/23 udp dport domain
	}
}
table ip6 x {
	chain y {
		type nat hook postrouting priority 0; policy accept;
		icmpv6 id 33-45
		ip6 daddr fe00::1-fe00::200 udp dport domain counter packets 0 bytes 0
		meta l4proto tcp masquerade to :1024
		iifname \"wlan0\" ct state established,new tcp dport vmap { ssh : drop, 222 : drop } masquerade
		tcp dport ssh ip6 daddr 1::2 ether saddr 00:0f:54:0c:11:04 accept
		ip6 daddr fe00::1-fe00::200 udp dport domain counter packets 0 bytes 0 masquerade
	}
}"

$NFT -f - <<< "$RULESET"
RULESET_JSON=$($NFT export vm json)
$NFT flush ruleset
$NFT import vm json <<< "$RULESET_JSON"
