#!/bin/bash

RULESET='
table inet test {
	set test {
		type ipv4_addr
		elements = { 1.1.1.1}
	}

	chain test {
		ip saddr @test counter accept
		ip daddr { 2.2.2.2} counter accept
	}
}'

set -e

$NFT -f - <<< $RULESET
rule_handle=$($NFT list ruleset -a | awk '/saddr/{print $NF}')
$NFT delete rule inet test test handle $rule_handle
$NFT delete set inet test test
$NFT -f - <<< $RULESET
