#!/bin/bash

# support for ifname in named sets

EXPECTED="table inet t {
	set s {
		type ifname
		elements = { \"eth0\" }
	}

	set sc {
		type inet_service . ifname
		elements = { \"ssh\" . \"eth0\" }
	}

	chain c {
		iifname @s accept
		oifname @s accept
		tcp dport . meta iifname @sc accept
	}
}"

set -e
$NFT -f - <<< $EXPECTED
