#!/bin/bash

# support for ifname in named sets

EXPECTED="table inet t {
	set s {
		type ifname
		elements = { \"eth0\" }
	}

	chain c {
		iifname @s accept
		oifname @s accept
	}
}"

set -e
$NFT -f - <<< $EXPECTED
