#!/bin/bash

set -e

RULESET="table ip x {
	map y {
		type ipv4_addr : ipv4_addr
		elements = { 10.141.0.1 : 192.168.0.2, * : 192.168.0.3 }
	}
	map z {
		type ipv4_addr : ipv4_addr
		flags interval
		elements = { 10.141.0.0/24 : 192.168.0.2, * : 192.168.0.3 }
	}
}"

$NFT -f - <<< $RULESET
$NFT delete element x y { \* : 192.168.0.3 }
$NFT add element x y { \* : 192.168.0.4 }
