#!/bin/bash

$NFT -f - <<EOF
table ip x {
        set s0 {
                type inet_service
                elements = { 20, 21, 22 }
                flags interval
                timeout 3s
        }
}
EOF

sleep 6

$NFT flush set ip x s0

$NFT -f - <<EOF
table ip x {
        set s1 {
                type ipv4_addr . inet_service
                elements = { 1.2.3.4 . 20, 1.2.3.5 . 21, 1.2.3.6 . 22 }
                flags interval
                timeout 3s
        }
}
EOF

sleep 6

$NFT flush set ip x s1

$NFT -f - <<EOF
table ip x {
        set s2 {
                type ipv4_addr
                elements = { 2.2.2.1, 2.2.2.2, 2.2.2.3 }
                timeout 3s
        }
}
EOF

sleep 6

$NFT flush set ip x s2
